// src/components/Greeting.jsx
export default function Greeting() {
	const currentTime = new Date()
	const currentHour = currentTime.getHours()

	let greeting = ""

	if (currentHour < 12) {
		greeting = "Buens días"
	} else if (currentHour < 18) {
		greeting = "Buenas tardes"
	} else {
		greeting = "Buenas noches"
	}

	return (
		<h1 className="text-3xl font-bold">{greeting}</h1>
	)
}

// src/components/Greeting.svelte
<script lang="ts">
    const currentTime = new Date()
    const currentHour = currentTime.getHours()

    let greeting = ''

    if (currentHour < 12) {
        greeting = 'Buens días'
    } else if (currentHour < 18) {
        greeting = 'Buenas tardes'
    } else {
        greeting = 'Buenas noches'
    }
</script>

<h1 class="text-3xl font-bold">{greeting}</h1>
